# Mise configuration for automation-scripts repository
# https://mise.jdx.dev/configuration.html

[env]
# Environment variables for the project
AUTOMATION_SCRIPTS_DIR = "{{config_root}}"

[tools]
# Shell scripting and validation tools
shellcheck = "0.11.0"        # Shell script static analysis
shfmt = "3.12.0"             # Shell script formatter

# Development tools
python = "3.12"              # For any Python-based utilities
node = "22"                  # For npm-based tools if needed
golang = "1.25.0"              # For Go-based tools (fd, etc.)

# Task runner
task = "latest"              # Taskfile task runner

# Documentation tools
mdbook = "latest"            # For building documentation

[tasks]
# Define common tasks that can be run with `mise run <task>`
validate = "find . -name '*.sh' -type f -not -path './.git/*' -exec shellcheck -S error {} +"
validate-all = "find . -name '*.sh' -type f -not -path './.git/*' -exec shellcheck {} +"
format = "shfmt -w -i 4 -ci ."
check-format = "shfmt -d -i 4 -ci ."
test = "./scripts/run-shellcheck.sh"
lint = { depends = ["validate"], description = "Run shellcheck validation (alias)" }

[settings]
# Mise settings
experimental = true
legacy_version_file = true  # Support .nvmrc, .python-version, etc.
always_keep_download = false
plugin_autoupdate_last_check_duration = "1 week"