name: Use Sync Labels Workflow

on:
  workflow_dispatch: # Allows manual triggering
  # You could also add 'schedule', 'push', etc. triggers if needed

jobs:
  sync-labels:
    uses: basher83/.github/.github/workflows/sync-labels.yml@main
    permissions:
      contents: read
      issues: write
    # with:
    #   label_definitions_url: "https://raw.githubusercontent.com/basher83/docs/main/mission-control/github-configs/label-definitions.yml" # optional, can omit for default
