name: Sync Labels from Central Definition

on:
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout basher83/docs repository
        uses: actions/checkout@v4
        with:
          repository: basher83/docs
          path: central-docs
          # Uncomment if private:
          # token: ${{ secrets.DOCS_REPO_PAT }}

      - name: Install yq v4
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Show yq version
        run: yq --version

      - name: Transform labels
        run: |
          yq eval '[.[] | .[]]' central-docs/mission-control/github-configs/label-definitions.yml > transformed-labels.yml
          echo "Transformed labels:"
          cat transformed-labels.yml
          echo "manifest_path=transformed-labels.yml" >> $GITHUB_OUTPUT

      - name: Sync labels to this repository
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: ${{ steps.transform.outputs.manifest_path }}
          prune: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
