name: Sync Labels from Central Definition

on:
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout basher83/docs repository
        uses: actions/checkout@v4
        with:
          repository: basher83/docs
          path: central-docs
          # Uncomment if private:
          # token: ${{ secrets.DOCS_REPO_PAT }}

      - name: Install yq v4
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Show yq version
        run: yq --version

      - name: Transform labels
        id: transform
        run: |
          echo "Working directory:"
          pwd
          echo "Checking if source file exists:"
          ls -la central-docs/mission-control/github-configs/label-definitions.yml
          echo "First few lines of source file:"
          head -20 central-docs/mission-control/github-configs/label-definitions.yml
          echo "Transforming labels..."
          yq eval '[.[] | .[]]' central-docs/mission-control/github-configs/label-definitions.yml > transformed-labels.yml
          echo "Checking if transformed file was created:"
          ls -la transformed-labels.yml
          echo "First few lines of transformed file:"
          head -20 transformed-labels.yml
          echo "Setting output variable with absolute path:"
          MANIFEST_PATH="$(pwd)/transformed-labels.yml"
          echo "manifest_path=${MANIFEST_PATH}" >> $GITHUB_OUTPUT
          echo "Verifying output was set to: ${MANIFEST_PATH}"

      - name: Sync labels to this repository
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: ${{ steps.transform.outputs.manifest_path }}
          prune: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
